version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: iris_systems_rec_task_development
    networks:
      - mysql-network

  rails:
    build: .
    ports:
      - "3000:3000"
    command: >
      bash -c "
      until mysqladmin ping -h mysql --silent; do sleep 0.5; done &&
      bin/rails db:prepare &&
      bundle exec rails server -b 0.0.0.0
      "

    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
